<script setup>
import { useRouter } from "vue-router";
const router = useRouter();
import axios from "axios";
import Swal from 'sweetalert2';

//const props = defineProps
defineProps(['notificationObj']);

function goToItem(itemId, notificationId, itemType) {
    console.log(itemId, notificationId, itemType)
    //console.log(notificationObj.article);
    axios.put(import.meta.env.VITE_API_ENDPOINT + `/notifications/${itemType}/read/${notificationId}`, 
    {}, {
        headers: { "Authorization": `Bearer ${localStorage.getItem("token")}` }
    })
        .then((response) => {
            if (response.status === 200) {
                console.log(response.data);
                if (itemType == "articles") {
                    router.push(`/news/${itemId}`);
                } else {
                    router.push(`/game/${itemId}`);
                }
            } else {
                console.log(response.data);
                Swal.fire({
                    background: "#252526",
                    color: "#FFF",
                    title: "There was an error!",
                    icon: "error",
                    html: response.data.message
                });
            }
        })
        .catch((error) => {
            console.log(error);
            Swal.fire({
                background: "#252526",
                color: "#FFF",
                title: "There was an error!",
                icon: "error",
                text: error.response.data.message
            });
        });
}
</script>

<template>
    <div class="card lg:card-side bg-base-100 shadow-xl mb-5">
        <div class="card-body">
            <div class="flex justify-between">
                <h2 class="card-title">{{ notificationObj.detail }}</h2>
                <div class="badge badge-outline">Generated on: {{ new Date(notificationObj.creationDate).toISOString().split("T")[0] }}</div>
            </div>
            <p v-if="notificationObj.article">Article title: {{ notificationObj.articleTitle }}</p>
            <p v-else>Game title: {{ notificationObj.gameTitle }}</p>
            <p>Generated by: {{ notificationObj.developer.username }}</p>
            <div class="card-actions justify-end">
                <button v-if="notificationObj.article" class="btn btn-primary" @click="goToItem(notificationObj.article._id, notificationObj._id, 'articles')">View article</button>
                <button v-else class="btn btn-primary" @click="goToItem(notificationObj.game._id, notificationObj._id, 'games')">View game</button>
            </div>
        </div>
    </div>
</template>